FROM archlinux

RUN pacman --noconfirm -Syu
RUN pacman --noconfirm -S neovim base-devel git zip unzip curl python wget

# Get my dotfiles
RUN mkdir /root/.config /root/Code
RUN git clone https://github.com/willnilges/dotfiles /root/Code/dotfiles
RUN bash /root/Code/dotfiles/symlink_setup.sh
RUN nvim --headless -c 'autocmd User PackerComplete quitall'
RUN nvim --headless -c 'PackerUpdate' -c 'quitall'
